# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addBooks.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMessageBox
import datetime
import pymysql

class Ui_insertBook(object):
    def setupUi(self, insertBook):
        insertBook.setObjectName("insertBook")
        insertBook.resize(400, 498)
        self.titleText = QtWidgets.QLabel(insertBook)
        self.titleText.setGeometry(QtCore.QRect(80, 40, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText.setFont(font)
        self.titleText.setObjectName("titleText")
        self.titleText_2 = QtWidgets.QLabel(insertBook)
        self.titleText_2.setGeometry(QtCore.QRect(80, 80, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_2.setFont(font)
        self.titleText_2.setAcceptDrops(False)
        self.titleText_2.setObjectName("titleText_2")
        self.titleText_3 = QtWidgets.QLabel(insertBook)
        self.titleText_3.setGeometry(QtCore.QRect(80, 200, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_3.setFont(font)
        self.titleText_3.setObjectName("titleText_3")
        self.titleText_4 = QtWidgets.QLabel(insertBook)
        self.titleText_4.setGeometry(QtCore.QRect(80, 120, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_4.setFont(font)
        self.titleText_4.setObjectName("titleText_4")
        self.titleText_5 = QtWidgets.QLabel(insertBook)
        self.titleText_5.setGeometry(QtCore.QRect(80, 160, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_5.setFont(font)
        self.titleText_5.setObjectName("titleText_5")
        self.titleText_6 = QtWidgets.QLabel(insertBook)
        self.titleText_6.setGeometry(QtCore.QRect(80, 240, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_6.setFont(font)
        self.titleText_6.setObjectName("titleText_6")
        self.titleText_7 = QtWidgets.QLabel(insertBook)
        self.titleText_7.setGeometry(QtCore.QRect(80, 280, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_7.setFont(font)
        self.titleText_7.setObjectName("titleText_7")
        self.titleText_8 = QtWidgets.QLabel(insertBook)
        self.titleText_8.setGeometry(QtCore.QRect(80, 320, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_8.setFont(font)
        self.titleText_8.setObjectName("titleText_8")
        self.titleText_9 = QtWidgets.QLabel(insertBook)
        self.titleText_9.setGeometry(QtCore.QRect(80, 360, 65, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleText_9.setFont(font)
        self.titleText_9.setAcceptDrops(False)
        self.titleText_9.setObjectName("titleText_9")
        self.pushButton = QtWidgets.QPushButton(insertBook)
        self.pushButton.setGeometry(QtCore.QRect(160, 420, 80, 40))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(insertBook)
        self.lineEdit.setGeometry(QtCore.QRect(170, 40, 140, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(insertBook)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 80, 140, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(insertBook)
        self.lineEdit_3.setGeometry(QtCore.QRect(170, 120, 140, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(insertBook)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 160, 140, 30))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(insertBook)
        self.lineEdit_5.setGeometry(QtCore.QRect(170, 200, 140, 30))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(insertBook)
        self.lineEdit_6.setGeometry(QtCore.QRect(170, 320, 140, 30))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.dateEdit = QtWidgets.QDateEdit(insertBook)
        self.dateEdit.setGeometry(QtCore.QRect(170, 280, 110, 30))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.year = datetime.datetime.now().year
        self.month = datetime.datetime.now().month
        self.day = datetime.datetime.now().day
        self.dateEdit.setDate(QtCore.QDate(self.year, self.month, self.day))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.spinBox = QtWidgets.QSpinBox(insertBook)
        self.spinBox.setGeometry(QtCore.QRect(170, 240, 50, 30))
        self.spinBox.setObjectName("spinBox")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(insertBook)
        self.doubleSpinBox.setGeometry(QtCore.QRect(170, 360, 65, 30))
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.retranslateUi(insertBook)
        self.pushButton.clicked.connect(self.enSure)
        QtCore.QMetaObject.connectSlotsByName(insertBook)

        self.msgBox_valueShortage = QMessageBox(QMessageBox.Information, "请输入所有内容", "请输入所有内容！", QMessageBox.Ok)
        self.msgBox_haveItems = QMessageBox(QMessageBox.Information, "该书目已存在", "该书目已存在！", QMessageBox.Ok)
        self.msgBox_insertFaild = QMessageBox(QMessageBox.Information, "录入失败", "录入信息失败，请重试！", QMessageBox.Ok)
        self.msgBox_succeed = QMessageBox(QMessageBox.Information, "录入成功！", "录入成功！", QMessageBox.Ok)

    def retranslateUi(self, insertBook):
        _translate = QtCore.QCoreApplication.translate
        insertBook.setWindowTitle(_translate("insertBook", "书籍录入"))
        self.titleText.setText(_translate("insertBook", "书目名称"))
        self.titleText_2.setText(_translate("insertBook", "isbn"))
        self.titleText_3.setText(_translate("insertBook", "出版社"))
        self.titleText_4.setText(_translate("insertBook", "作者"))
        self.titleText_5.setText(_translate("insertBook", "分类"))
        self.titleText_6.setText(_translate("insertBook", "入库数量"))
        self.titleText_7.setText(_translate("insertBook", "上架日期"))
        self.titleText_8.setText(_translate("insertBook", "书籍位置"))
        self.titleText_9.setText(_translate("insertBook", "书籍价格"))
        self.pushButton.setText(_translate("insertBook", "确定"))


    def enSure(self):
        title = self.lineEdit.text()
        isbn = self.lineEdit_2.text()
        author = self.lineEdit_3.text()
        publisher = self.lineEdit_4.text()
        classification = self.lineEdit_5.text()
        book_num = self.spinBox.value()
        in_shelf_time = self.dateEdit.date().toString(Qt.ISODate)
        book_position = self.lineEdit_6.text()
        price = self.doubleSpinBox.value()
        if (title == "" or isbn == "" or author == "" or publisher == "" or classification == "" or book_num == 0 or book_position == "" or price == 0.00):
            self.msgBox_valueShortage.show()
        else:
            conn = pymysql.connect(host='localhost', port=3306, user='root', password='admin', db='libMS',
                                   use_unicode=True, charset='utf8')
            cur = conn.cursor()
            sqlSelect = "select * from books_catalogue where isbn = '%s' and publisher = '%s';" %(isbn, publisher)
            sqlInsert = "insert into books_catalogue(title, isbn, author, publisher, classifaction, book_num, in_shelf_time, book_position, price)" \
                  " values('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s');"%(title, isbn, author, publisher, classification,
                                                                              book_num, in_shelf_time, book_position, price)

            selectRow = cur.execute(sqlSelect)
            if selectRow == 0:
                try:
                    cur.execute(sqlInsert)
                    conn.commit()
                    self.msgBox_succeed.show()
                    self.lineEdit.clear()
                    self.lineEdit_2.clear()
                    self.lineEdit_3.clear()
                    self.lineEdit_4.clear()
                    self.lineEdit_5.clear()
                    self.lineEdit_6.clear()
                    self.spinBox.setValue(0)
                    self.doubleSpinBox.setValue(0.00)
                except:
                    self.msgBox_insertFaild.show()
            else:
                self.msgBox_haveItems.show()
            cur.close()
            conn.close()
